/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'skirsanov' at '9/1/15 6:22 PM' with Gradle 2.6
 *
 * @author skirsanov, @date 9/1/15 6:22 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class BitSetTestSuite extends FunSuite {


  test("simple test cases") {
    assert(BitSetMix.bestMatch(1) == 2)
    assert(BitSetMix.bestMatch(2) == 1)
    assert(BitSetMix.bestMatch(3) == 5)

    assert(BitSetMix.bestMatch(Math.pow(2, 32).toLong - 2) == Math.pow(2, 32).toLong - 3)
  }

  test("corner cases") {
    intercept[IllegalArgumentException] {
      BitSetMix.bestMatch(-1)
    }
    intercept[IllegalArgumentException] {
      BitSetMix.bestMatch(0)
    }
    intercept[IllegalArgumentException] {
      BitSetMix.bestMatch(Math.pow(2, 32).toLong - 1)
    }
    intercept[IllegalArgumentException] {
      BitSetMix.bestMatch(Math.pow(2, 32).toLong + 1)
    }
  }
}
